"""Deterministic, question-only display titles for Error records."""

from __future__ import annotations

import re


_MAX_TITLE_LENGTH = 28

_MATH_BLOCK_RE = re.compile(r"\\{1,2}\[(?:.|\n)*?\\{1,2}\]", re.DOTALL)
_MATH_PAREN_RE = re.compile(r"\\{1,2}\((?:.|\n)*?\\{1,2}\)", re.DOTALL)
_DOLLAR_BLOCK_RE = re.compile(r"\$\$(?:.|\n)*?\$\$", re.DOTALL)
_DOLLAR_INLINE_RE = re.compile(r"(?<!\\)\$(?!\$)[^\n]*?(?<!\\)\$(?!\$)")
_LEAKED_LATEX_COMMAND_RE = re.compile(
    r"(?<![A-Za-z])(?:d?frac|tfrac|sqrt|text|boxed|mathrm|mathbf|mathbb|"
    r"operatorname|left|right|begin|end|overline|underline)\s*(?=[{[(])"
)
_UNSAFE_TITLE_RE = re.compile(
    r"(?:\\|\$|`|\*{2}|_{2}|<[^>]*>|"
    r"(?<![A-Za-z])(?:d?frac|tfrac|sqrt|text|boxed|mathrm|mathbf|mathbb|"
    r"operatorname|left|right|begin|end|overline|underline)\s*[{[(])"
)


def _plain_question(value: str | None) -> str:
    value = value or ""
    value = re.sub(r"```.*?```", " ", value, flags=re.DOTALL)
    value = re.sub(r"!\[[^]]*\]\([^)]*\)|\[([^]]+)\]\([^)]*\)", r"\1", value)
    # Math is useful in the body but makes a poor title.  Remove complete
    # expressions first so old fallback titles cannot leak ``frac{...}`` or
    # other TeX command fragments into the history/sidebar.
    for pattern in (_MATH_BLOCK_RE, _MATH_PAREN_RE, _DOLLAR_BLOCK_RE, _DOLLAR_INLINE_RE):
        value = pattern.sub(" ", value)
    value = re.sub(r"<[^>\n]*>", " ", value)
    value = re.sub(r"\\+[A-Za-z]+", " ", value)
    value = _LEAKED_LATEX_COMMAND_RE.sub(" ", value)
    value = re.sub(r"[*_~`#>$\\{}]+", "", value)
    value = re.sub(r"\s+", " ", value).strip()
    return re.sub(r"^(?:题目|问题|解答)\s*[:：]\s*", "", value)


def _short(value: str) -> str:
    value = re.sub(r"\s+", " ", value).strip(" ，,;；:：。.!！?？")
    if not value:
        return "未命名错题"
    return value if len(value) <= _MAX_TITLE_LENGTH else value[: _MAX_TITLE_LENGTH - 1].rstrip() + "…"


def display_title_for_question(question: str | None) -> str:
    """Return a stable short name without inspecting the user's thoughts.

    The title is deliberately derived only from the saved question.  A few
    math-specific labels make long questions easier to scan; all other input
    uses its first meaningful line/sentence as a deterministic fallback.
    """
    value = _plain_question(question)
    if not value:
        return "未命名错题"

    function_match = re.search(
        r"(?<![A-Za-z0-9_])([A-Za-z][A-Za-z0-9_]*\s*\([^)]{1,24}\))",
        value,
    )
    if "最值" in value or "最大值" in value or "最小值" in value:
        if function_match:
            return _short(f"{function_match.group(1).replace(' ', '')} 的最值判断")
        return "函数最值判断"
    if "值域" in value or "范围" in value:
        if "三角" in value or re.search(r"\b(?:sin|cos|tan)\b", value, re.I):
            return "三角函数值域判断"
        return "函数范围判断"
    if "概率" in value:
        return "概率条件判断"
    if "正交" in value or ("向量" in value and "垂直" in value):
        return "向量正交性判断"
    if "导数" in value or "单调" in value:
        return "函数单调性判断"
    if "方程" in value:
        return "方程求解"

    first_sentence = re.split(r"[。！？!?]", value, maxsplit=1)[0]
    candidate = first_sentence if len(first_sentence) >= 4 else value
    return _short(candidate)


def is_safe_display_title(value: str | None) -> bool:
    """Return whether a persisted system title is safe to show unchanged.

    Titles are generated by the application today, but older databases may
    contain titles produced before math/Markdown plainification was fixed.
    Keep ordinary user-facing titles stable while identifying those legacy
    fragments for the one-time schema backfill and the Web defense-in-depth
    fallback.
    """
    return bool(value and value.strip() and not _UNSAFE_TITLE_RE.search(value))


def context_excerpt(value: str | None, limit: int = 116) -> str:
    """Return a compact, non-Markdown context label for a collapsed section."""
    compact = _plain_question(value)
    if len(compact) <= limit:
        return compact
    return compact[: limit - 1].rstrip() + "…"
